<a href="https://colab.research.google.com/github/adenikeadewumi/AWS-AI-ML-program/blob/main/ML_Class_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

#Importations
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:

#data generation
# Generating Synthetic Data
np.random.seed(42)
experience = np.arange(1, 21)
salary = 30000 + (experience * 5000) + np.random.randint(-2000, 2000, size=20)

df = pd.DataFrame({'Years': experience, 'Salary': salary})
print(df.tail())#This gives you the last five rows of df
df.head()#This gives you the first five rows of df

    Years  Salary
15     16  111444
16     17  116171
17     18  120919
18     19  126735
19     20  128130

   Years  Salary
0      1   36174
1      2   41507
2      3   43860
3      4   49294
4      5   54130

In [3]:
df.head()

   Years  Salary
0      1   36174
1      2   41507
2      3   43860
3      4   49294
4      5   54130

In [4]:
df.shape

(20, 2)

In [ ]:
#Solution to classwork